apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-3263f7
  labels:
    component: nodejs
    app: coda-test-task
    version: 3263f7
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nodejs
      app: coda-test-task
      version: 3263f7
  template:
    metadata:
      labels:
        component: nodejs
        app: coda-test-task
        version: 3263f7
    spec:
      containers:
      - name: coda-test-app
        image: 210195853677.dkr.ecr.us-east-1.amazonaws.com/coda-test-task:3263f7
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m